### ISSUE TITLE
Encoding problem when filename contains chinese

### ISSUE THREAD

**Issue by zeyuLiang** [amartel/redmine_scm_extensions#15]
Hi.
First of all, thanks to this great plugin, we built a cloud-like file-system for company.
We are facing this encoding problem when filename contains chinese word.
For example,upload a file name '编辑2.TXT.bak'
```
svn: warning: W160013: URL 'file:///var/svn/redmine_advice.0/%E7%BC%96%E8%BE%912.TXT.bak' non-existent in revision 10
svn: E200009: Could not list all targets because some targets don't exist
svn: E000022: Can't convert string from native encoding to 'UTF-8':
svn: E000022: /tmp/20150202-9529-17bxk4e/?\231?\188?\150?\232?\190?\1452.TXT.bak
```
The system locale encoding is fine
```
rails@earth:/rails_apps/redmine/current$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```
We try to  simulate the svn process in irb, it works which makes me more confuse.
Hope you can offer some help~^_^

**Comment by amartel** [comment]
Hi,
Sorry but I can't make some tests (chinese is not my native language)...
I took a look at my source code and I use different methods when the file is uploaded using ajax (drag & drop) or using the classical "select file" button.
Have you got the error in all cases?

**Comment by zeyuLiang** [comment]
Finally, we solved the problem by changing the user for nginx process which actually runs the shell command.
What a stupid question~~
